### ISSUE TITLE
Opt our users out of FLoC tracking

### ISSUE THREAD

**Issue by robinwhittleton** [standardebooks/web#123]
Open question: do we want to opt our users out of Google tracking?

https://spreadprivacy.com/block-floc-with-duckduckgo/ for more info, but the gist is Google trialing a new system that attempts to track small groups of users rather than individuals, by assigning them on-device into cohorts, potentially preserving user privacy.

A more cynical reading is that Apple and Mozilla have / are blocking 3rd party cookies, leaving the ad industry up shit creek, and Google is desperately trying to do the minimum possible to look like a reasonable actor, without breaking their ad business.

Anyway, we can with the `Permissions-Policy: interest-cohort=()` header choose to opt our users out of FLoC tracking, meaning that standardebooks.org won’t be used as a targeting mechanism for the cohort generation. This sounds like a good idea to me, but thoughts?

**Comment by acabal** [comment]
I agree that FLoC sounds terrible, but I'm hesitant to start start sending company-specific HTTP headers. This sounds like something better achieved at the browser level (i.e., stop using Chrome) and through user education (maybe wishful thinking but the tech crowd seems suitably upset at the idea) rather than forcing websites with no relationship with Google to start jumping every time Google has a bad idea. Because then we'd have to jump when Bing does something stupid, Amazon, etc. The Wikipedia article suggests FLoC has been named in 15 antitrust suits last month so maybe its life won't be so long after all.

**Comment by robinwhittleton** [comment]
Reasonable argument 🙂
