### ISSUE TITLE
Order of scan sites

### ISSUE THREAD

**Issue by vr8hub** [standardebooks/web#171]
We currently say in the step by step guide to use IA, Hathi, and Google, in that order. Given that we now want to download the scans, and that Hathi prevents that in a lot of cases, do we want to reverse the last two?

**Comment by acabal** [comment]
No, because 95% of the time the scans on Hathi are at Google Books anyway and they provide a download link for the Google Books copy. I prefer Hathi as a permalink in the ebook because of Google's habit of disappearing services overnight. I don't have any reason to think Google Books is going away anytime soon, but Google has a history of doing that, so they're the least trustworthy of the three.
