### ISSUE TITLE
Mailing list inaccessible

### ISSUE THREAD

**Issue by rnkn** [standardebooks/web#18]
Hello,

The Google mailing list is inaccessible for me, giving the error:

> This group either doesn't exist, or you don't have permission to access it. If you're sure this group exists, contact the owner of the group and ask them to give you access.

As an alternative to Google's ~~data harvesting tool~~ mailing list you might like to consider:

- https://groups.io/
- https://sr.ht/

🙂

**Comment by acabal** [comment]
Strange, seems like my Google account was temporarily locked out for some reason, thus disabling the group. It should be fixed now.

I would like to switch to a self hosted mailing list solution in the long term, however I don't have time to do that any time soon. I would prefer to do something self hosted instead of just using a different 3rd party. Suggestions and pull requests are welcomed.

**Comment by rnkn** [comment]
> I would like to switch to a self hosted mailing list solution in the 
> long term, however I don't have time to do that any time soon. I would 
> prefer to do something self hosted instead of just using a different 
> 3rd party. Suggestions and pull requests are welcomed.

I think self-hosting email and/or a mailing list is tricky business. I 
guess there are really two parts though, the mail server and the list 
archive; would you self-host both parts?

One of the problems with Google Groups is that there is no (easy) way to 
export the archive.

**Comment by acabal** [comment]
Yes. I'm sure we can figure out some way to script an export out of Google Groups. Ultimately I would like all SE discussion and project management to be hosted on our own servers.
