### ISSUE TITLE
Proposal: remove the pagination

### ISSUE THREAD

**Issue by robinwhittleton** [standardebooks/web#4]
I tend to view pagination as an anti-pattern: a way of solving the website’s lack of resources at the expense of usability. Now obviously there are use cases for pagination (large numbers of results, expense of generating each result, cost of rendering each result to the user) but I don’t think any apply here.

The cost to the user of pagination is the inability to find in page, and the wait for each further page to load instead of just scrolling down. A typical alternative would be infinite scroll (automatic or “Click to load more results”) but I don’t even think we need that here.

At the moment the library is <250 books. As an optimistic estimate, this may grow to ~1000 titles over the next 5 years. The rendering cost for each result is pretty much all in the images, and they’re a fixed size for each one. So I’d like to suggest the following course of action:

1. Remove the pagination functionality and display all books on a single page, allowing the user to scroll through them.
2. Add `width` and `height` attributes to the images so that the browser knows the aspect ratio for layout (width can still be overridden with CSS but the browser can calculate aspect ratio from that for offscreen layout).
3. (optionally) Use some form of lazy loading for the images. This could be Chrome’s [upcoming native implementation](https://css-tricks.com/a-native-lazy-load-for-the-web-platform/), or a JS solution. Could potentially use some sort of skeleton ‘unloaded’ background too.

Thoughts? Obviously I’m happy to PR this if people want it.

**Comment by acabal** [comment]
Interesting proposal. However my end goal is to not have JS on the page at all. (Or at least have a fully functional site when the use has JS disabled.) Right now it's only there for syntax highlighting and we can drop that once we start compiling the manual from RST.

Pretty much all of the infinite scroll type solutions require JS and personally I almost always find them annoying and quirky. A serious problem is using the back button to return to the same place you started from in infinite scroll. Many websites still haven't figured out how to do that so I'm not sure it's a simple issue. Then we'd have to set up web services to populate the pages. Plus on mobile browsers infinite scroll is usually plagued by viewport jumpiness and general poor performance.

We could increase the page size I suppose. But as for showing all the books on one page, I think that also has a psychological effect: it makes SE seem like a very small project, if you can scroll through its complete corpus in a few seconds.

Now, we *are* a small project, but we don't want to *seem* like one. Small projects are less likely to get new contributors, because people don't take them as seriously. Pages give us an illusion that SE is bigger than it currently is; that there's even more books just behind the next page. (And indeed it's working, because more than a few people have complained that we need better sorting and filtering!)

If anything, I think filtering by SE category would be a good next step. But even then we can get in the situation where a person selecting a less-popular category might only see one book, making us appear small-time. Also I think the UI for a multi-checkbox select would be quite difficult or even impossible to achieve without JS.

**Comment by robinwhittleton** [comment]
I wholeheartedly approve of removing JS from the site whereever possible! Infinite scroll solutions need it for extremely large sets of results, but we don’t have that. However I do sympathise in trying to make it seem like our corpus is bigger than it actually is :)

Let‘s close this issue in favour of seperate ones for categories and series (I’d like to be able to see all the Holmes or Lupins for example).

**Comment by acabal** [comment]
I like that idea... categorize by series. Maybe we can add some kind of series metadata to each ebook? `<meta property="se:series">Sherlock Holmes Mysteries</meta>`?
