### ISSUE TITLE
KoboTouch Extended driver for Calibre transfers kepub files directly

### ISSUE THREAD

**Issue by rsking** [standardebooks/web#452]
After experience, when you store a file in calibre as a `.kepub` file (strip off the `.epub` part), then transfer to a Kobo device when using the [KoboTouchExtended](https://github.com/jgoguen/calibre-kobo-driver) driver it transfers the file as a `.kepub.epub` file (i.e. same size as the downloaded `.kepub` file). Stripping off the `.epub` extension might not be required, but is required if you want to store both the `.epub` and `.kepub` files in calibre.

This is in contrast to the advice [here](https://github.com/standardebooks/web/blob/7b676269a8b1dd9b8f8f55c435d429ae7167fac1/www/help/how-to-use-our-ebooks.php#L103).

It could be convoluted way of getting the files in (I store both the .epub and .kepub files, so this is easy for me), but we could update the instructions for this as well.

**Comment by acabal** [comment]
I think that's too complicated. People are downloading a file, we don't want to have to instruct them to change file extensions for some reason. Easier to just transfer the single file they downloaded from us via USB cable which many people do anyway. (Or, patch the driver/Calibre to not apply a duplicate conversion to a file that is already a kepub. Maybe this has already been done since we wrote these instructions?)

**Comment by rsking** [comment]
Yep... works for me, but am fine to leave the instructions as they are...
