### ISSUE TITLE
Request for quick Foliate review

### ISSUE THREAD

**Issue by digitalethics** [standardebooks/web#69]
I have just looked at your excellent manual for [typography](https://standardebooks.org/manual/1.0.0/8-typography). It would be great to work more closely with one another to maximize the aesthetic outcome for both projects. Would you mind reviewing [Foliate](https://github.com/johnfactotum/foliate) in terms of how well Standard Ebooks are rendered and raise any usability issues that you may come across in this process? You would probably notice any formatting and typography issues much quicker and your feedback on this topic would be greatly appreciated.

**Comment by acabal** [comment]
Sure, but are you a Foliate maintainer? I don't want to barge in on the project with a review that a maintainer didn't ask for.

**Comment by digitalethics** [comment]
> Sure, but are you a Foliate maintainer? I don't want to barge in on the project with a review that a maintainer didn't ask for.

Thanks a lot for being open to this. I'm not a Foliate maintainer but I'm happy to contribute to the project because I get to learn so much in return. I also feel that projects like yours and Foliate are of such outstanding quality, that I believe we should try to connect and support each other because we will all thrive with more community support.

You are actually the first one I ask for a quick review, simply because I feel Foliate has matured enough in terms of how it _presents_ ebooks to its readers. And since OPDS implementations are currently being worked on, it would make sense to begin with your review now to support the iterative design process. At a later stage, I'm planning to ask friends and colleagues to conduct code audits (security and privacy), and to begin with more informal usability tests from people in academia. For now, however, external usability and security audits are too early. 

@johnfactotum Would you be okay that Alex takes a look at Foliate at the current stage of its development? Are you okay with me reaching out into communities like this and getting more feedback and perhaps more people involved in your project?

**Comment by johnfactotum** [comment]
Sure! I would appreciate reviews. I think most formatting should work correctly. There are a few of issues that I can think of at the moment:
- Standard Ebooks uses transparent images, which works great with sepia themes, but not so well with dark themes; the workaround for now is to use "Invert" in Foliate
- `font-variant: small-caps` does not use real small caps even when they are provided by the font (this is a WebKit bug; see https://github.com/johnfactotum/foliate/issues/100)
- When looking up words in Wiktionary, the `xml:lang` attribute is not used; instead it always uses the language set in the book's metadata
- Standard Ebooks provides rich [metadata](https://standardebooks.org/manual/1.0.0/9-metadata), but most of them are being ignored in Foliate, due to Epub.js having only very basic metadata support. I've added a patch for extracting `dc:subject` but that's it so far.

**Comment by acabal** [comment]
> Standard Ebooks uses transparent images, which works great with sepia themes, but not so well with dark themes; the workaround for now is to use "Invert" in Foliate.

For images that are SVGs/PNGs that are only black on a transparent background, we include `epub:type="se:color-depth.black-on-transparent"`. This is meant as a hint to the reading system that those images can be safely inverted for dark themes. (Not all images are suitable to be inverted, for example full-color images or even grayscale images.) I think our titlepages are missing that semantic at the moment but that's something we should add in the future.

I'll set this aside and do a review a little later, and send over any notes. From my quick glance at the app it looks like it has pretty good support already.

**Comment by johnfactotum** [comment]
I just noticed that for the "compatible" EPUB files, the images are already inverted correctly, because Foliate supports the `__ibooks_internal_theme` attribute.

**Comment by robinwhittleton** [comment]
@johnfactotum in an unlaunched version of the toolkit I’ve removed the Books theme hack in favour of a prefers-color-scheme media query. Does Foliate also support this?

**Comment by johnfactotum** [comment]
@robinwhittleton Yes, it does! It gets the feature "for free" because WebKitGTK automatically sets `prefers-color-scheme` to `dark` when using a dark variant GTK theme. For reference, see https://bugs.webkit.org/show_bug.cgi?id=196685.

**Comment by johnfactotum** [comment]
One thing that always bugged me is that certain text in Standard Ebook books will break in the middle of a line in Foliate. It seems to be caused by `display: inline-block;`, which doesn't work very well within CSS multicol in WebKitGTK.

For example, this famous poem in *Alice’s Adventures in Wonderland* is is rendered like this in Foliate:
![image](https://user-images.githubusercontent.com/50942278/147870655-e5bedb34-094a-48ea-912f-d3bbf8e07679.png)

And this seems to be purely a quirk of how `inline-block` works in WebKit. It will try to avoid breaking inside the element, but if that's not possible, it will just break at the column boundary even if that means breaking inside a line.

When using Epub.js in Firefox, it's even worse. When the `inline-block` element fails to fit inside the column, the element will simply overflow the column container. 
![image](https://user-images.githubusercontent.com/50942278/147870481-db07244c-12f7-4152-a45d-60a95f2d4a34.png)

I'm not sure if which, if any, of Firefox and WebKit's rendering is correct. But it does mean that column-based reading systems will all render the poem incorrectly.

Another instance where stuff is being broken in the middle of the line is `display: flex;`. Firefox seems to be able to handle this without any issues, but in WebKit, you get similar behavior as `inline-block`:
![image](https://user-images.githubusercontent.com/50942278/147870648-9fe30c8c-ef1f-4e7d-9272-e42705e78852.png)

**Comment by acabal** [comment]
Yes, I'm aware of this issue. We have the same problem when trying to do full-page illustrations that have captions. In Webkit the captions run off the page for the same reason.

IMHO this is a rendering bug. The renderer should know what to do with overflow if it bleeds on to the next page. But, since actual pagination has never been a big priority for web renderers (also see the poor support for `break-*` CSS properties) I'm not surprised these problems still exist.

Unfortunately we can't work around this because there's no way to simplify or change the CSS without breaking the desired layout. This is something to bring up with Webkit or perhaps directly with iBooks as they're probably the biggest user of full-blown Webkit in an ereading context, and they have the resources to fix Webkit bugs.
